#pragma once
// 함수 원형
	void CppBasic();
	void Variable();
	void Arithmetic();
	void Increment();
	void CompareFunction();
	void Logical();
	void IfFunctionDesc();
	void IfFunctionEx01();
	void IfFunctionEx02(int);
	void IfNestDesc();
	void IfNestEx01();
	void IfNestEx02();
	void SwitchEx();
	void ForFunctionDesc();
	void ForFunctionEx01();
	void ForFunctionEx02();
	void ForFunctionEx03();
	void ForFunctionEx04();
	void WhileFunctionDesc();
	void WhileFunctionEx01();
	void ParameterFunction(int Param1, int Param2);
	int ReturnFunction();
	int ParamReturn(int Param1, int Param2);
	void Sum();
	void PrintArray();
	void SumArray();
	char Grade(int);
	void ProcessScore();
	void stringArray();
	void BubbleSort();
	void MultiArray();
	void DefineStructure();
	void StructureArray();
	void Enumeration();
	void EnumerationEnum();
	void EvenOdd();
	void Homework01();
	void PrintEven();
	void HomeWork02();
	void Median(float, float);
	void StandardGrade();
	void ArraySum();
	void Sort();
	void Reverse();
	int Absolute(int);
	void GradeTest();
	void GradeHomeWork();
	void Grade();
	void PonterVar();
	void PointerCalc();
	void PointerArray();
	void DynamicAlloc();
	void DynamicAlloc2();
	void DynamicArray();
	void InputArraySize();
	void InputBall();
	void DiceGame();
	void DefineClass();
	void PrintPlayer();
	void PrintAirplane();
	void DynamicAirplane();
	void Score();



